name: mhu
version: 1.0.0
description: Command line utility to help with Dart and Flutter development

executables:
  mhu:

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  args: any
  http: any
  path: any
  xml: any
  yaml: any
  pubspec: any
  mhu_dart_commons: ^1.0.2

dev_dependencies: 
  test: any

